# Generated by Django 4.2.3 on 2023-07-29 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_cart_product_delete_product_cart'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'ordering': ('product', 'quantity'), 'verbose_name': 'Корзина', 'verbose_name_plural': 'Корзины'},
        ),
    ]
