# Generated by Django 4.2.3 on 2023-07-30 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_cart_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='image',
            field=models.FileField(blank=True, upload_to='static/img/comments'),
        ),
    ]
