# Generated by Django 4.2.3 on 2023-07-31 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_testimonial_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(db_index=True, max_length=150, verbose_name='Имя')),
                ('email', models.EmailField(max_length=200, verbose_name='Электронная почта')),
                ('password', models.CharField(max_length=100, verbose_name='Пароль')),
                ('password2', models.CharField(max_length=100, verbose_name='Подтвердите пароль')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'ordering': ('login', 'email', 'password', 'password2'),
            },
        ),
    ]
